import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: `${Colors.black}66`,
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius['3xl'],
    borderTopRightRadius: BorderRadius['3xl'],
    gap: Spacing.md,
    padding: Spacing.lg,
    maxHeight: '88%',
    ...Shadows.lg,
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    height: 4,
    marginBottom: Spacing.xs,
    width: 44,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eyebrow: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  title: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.title,
    fontWeight: '800',
    marginTop: Spacing.xs,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  productTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '600',
    lineHeight: 22,
  },
  sectionLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  eventList: {
    gap: Spacing.sm,
    maxHeight: 220,
  },
  eventItem: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    gap: 2,
    padding: Spacing.base,
  },
  eventItemActive: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  eventItemTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
  eventItemMeta: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
  },
  emptyBox: {
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.lg,
  },
  emptyText: {
    color: Colors.slate500,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  fieldRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  fieldCol: {
    flex: 1,
    gap: Spacing.xs,
  },
  fieldLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
  },
  input: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    minHeight: 48,
    paddingHorizontal: Spacing.base,
  },
  helperError: {
    color: Colors.error,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
  },
  guaranteeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: Colors.slate300,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    height: 24,
    justifyContent: 'center',
    marginTop: 1,
    width: 24,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  guaranteeText: {
    color: Colors.onSurfaceVariant,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    minHeight: 52,
    ...Shadows.colored(Colors.primary),
  },
  disabledButton: {
    opacity: 0.5,
  },
  submitText: {
    color: Colors.white,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.bodyXl,
    fontWeight: '800',
  },
});
