import { StyleSheet } from 'react-native';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../constants/theme';

export const styles = StyleSheet.create({
  shell: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['3xl'],
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.xl,
    paddingBottom: Spacing.xl,
    gap: Spacing.md,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    color: Colors.onSurface,
    fontSize: FontSize.title,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  minBidLabel: {
    color: Colors.slate500,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    marginTop: Spacing.xs,
  },
  closeButton: {
    padding: Spacing.xs,
  },
  section: {
    gap: Spacing.xs,
  },
  sectionLabel: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '600',
    paddingLeft: Spacing.xs,
  },
  mainInputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.secondaryContainer,
    borderRadius: BorderRadius['2xl'],
    paddingHorizontal: Spacing.base,
    borderWidth: 2,
    borderColor: Colors.auctionGreen,
    ...Shadows.sm,
  },
  mainCurrency: {
    color: Colors.auctionGreen,
    fontSize: FontSize.titleLg,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '800',
    marginRight: Spacing.xs,
  },
  mainInput: {
    flex: 1,
    paddingVertical: 18,
    color: Colors.onSurface,
    fontSize: FontSize.titleLg,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  subInputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius['2xl'],
    paddingHorizontal: Spacing.base,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  subCurrency: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
    marginRight: Spacing.xs,
  },
  subInput: {
    flex: 1,
    paddingVertical: 12,
    color: Colors.onSurface,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '600',
  },
  quickBidRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  quickBidChip: {
    flex: 1,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xs,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.surfaceContainerLowest,
    borderWidth: 1.5,
    borderColor: Colors.surfaceContainerHigh,
    alignItems: 'center',
    gap: 2,
    ...Shadows.sm,
  },
  quickBidChipText: {
    color: Colors.slate500,
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bodySemiBold,
    textTransform: 'uppercase',
  },
  quickBidChipValue: {
    color: Colors.onSurface,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  stateCard: {
    borderRadius: BorderRadius.xl,
    backgroundColor: `${Colors.primary}10`,
    borderWidth: 1,
    borderColor: `${Colors.primary}20`,
    padding: Spacing.base,
    gap: Spacing.xs,
  },
  stateTitle: {
    color: Colors.primary,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  stateBody: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  walletGateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderRadius: BorderRadius.xl,
    backgroundColor: `${Colors.error}12`,
    borderWidth: 1,
    borderColor: `${Colors.error}24`,
    padding: Spacing.base,
  },
  walletGateText: {
    flex: 1,
    color: Colors.error,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  feeEstimatesContainer: {
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.xl,
    padding: Spacing.base,
    gap: Spacing.xs,
  },
  feeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  feeRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.outlineVariant,
    paddingTop: Spacing.xs,
  },
  feeRowTotal: {
    borderTopWidth: 1,
    borderColor: Colors.outlineVariant,
    paddingTop: Spacing.sm,
    marginTop: Spacing.xs,
  },
  feeLabel: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  feeLabelTotal: {
    color: Colors.onSurface,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  feeValue: {
    color: Colors.onSurface,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '600',
  },
  feeValueTotal: {
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  feeValueAccent: {
    color: Colors.auctionGreen,
  },
  feeValueError: {
    color: Colors.error,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.auctionGreen,
    borderRadius: BorderRadius['2xl'],
    paddingVertical: 18,
    ...Shadows.colored(Colors.auctionGreen),
    marginTop: Spacing.xs,
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    color: Colors.white,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  footerHint: {
    textAlign: 'center',
    color: Colors.slate400,
    fontSize: FontSize.xs,
    fontFamily: FontFamily.body,
    marginTop: -Spacing.xs,
  },
});
