import { StyleSheet } from 'react-native';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../constants/theme';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['3xl'],
    padding: Spacing.lg,
    gap: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.surfaceContainerHigh,
    ...Shadows.md,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.base,
    alignItems: 'flex-start',
  },
  overline: {
    color: Colors.primary,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  currentPriceLabel: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.body,
    fontFamily: FontFamily.body,
    marginTop: Spacing.xs,
  },
  currentPriceValue: {
    color: Colors.onSurface,
    fontSize: FontSize.display,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '800',
    marginTop: Spacing.sm,
  },
  timerShell: {
    minWidth: 132,
    alignItems: 'flex-end',
    gap: Spacing.sm,
  },
  timerBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.primary}14`,
  },
  timerBadgeEnded: {
    backgroundColor: `${Colors.error}14`,
  },
  timerBadgeText: {
    color: Colors.primary,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  timerBadgeTextEnded: {
    color: Colors.error,
  },
  timerEndedText: {
    color: Colors.error,
    fontSize: FontSize.titleSm,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '800',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  metricCard: {
    width: '48%',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.base,
    gap: Spacing.sm,
  },
  metricLabel: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  metricValue: {
    color: Colors.onSurface,
    fontSize: FontSize.subheading,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  metricValueAccent: {
    color: Colors.auctionGreen,
  },
  activityStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderRadius: BorderRadius.xl,
    backgroundColor: `${Colors.accent}14`,
    padding: Spacing.base,
  },
  activityTextWrap: {
    flex: 1,
    gap: 2,
  },
  activityTitle: {
    color: Colors.accent,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  activityBody: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  walletStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.base,
    borderRadius: BorderRadius.xl,
    backgroundColor: `${Colors.secondary}14`,
    padding: Spacing.base,
  },
  walletLabel: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  walletValue: {
    color: Colors.secondary,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  calloutCard: {
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.base,
    gap: Spacing.sm,
  },
  sellerModeCard: {
    backgroundColor: `${Colors.primary}10`,
    borderWidth: 1,
    borderColor: `${Colors.primary}20`,
  },
  winnerCard: {
    backgroundColor: `${Colors.secondary}16`,
    borderWidth: 1,
    borderColor: `${Colors.secondary}2E`,
  },
  loserCard: {
    backgroundColor: `${Colors.error}12`,
    borderWidth: 1,
    borderColor: `${Colors.error}24`,
  },
  calloutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  calloutTitle: {
    color: Colors.onSurface,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '700',
  },
  calloutBody: {
    color: Colors.onSurfaceVariant,
    fontSize: FontSize.body,
    lineHeight: 20,
    fontFamily: FontFamily.body,
  },
  resultButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    paddingVertical: 14,
    ...Shadows.colored(Colors.primary),
  },
  resultButtonText: {
    color: Colors.white,
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
});
