import { StyleSheet } from 'react-native';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../constants/theme';

export const styles = StyleSheet.create({
  heroCard: {
    borderBottomLeftRadius: BorderRadius['4xl'],
    borderBottomRightRadius: BorderRadius['4xl'],
    overflow: 'hidden',
    backgroundColor: Colors.surfaceContainerLow,
  },
  heroImage: {
    width: '100%',
    height: 360,
    backgroundColor: Colors.surfaceContainerLow,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: `${Colors.slate900}96`,
  },
  backButton: {
    position: 'absolute',
    top: 56,
    left: Spacing.base,
    width: 44,
    height: 44,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.white}E6`,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.md,
  },
  topMetaRow: {
    position: 'absolute',
    top: 58,
    right: Spacing.base,
    alignItems: 'flex-end',
    gap: Spacing.sm,
  },
  topMetaGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: BorderRadius.full,
  },
  statusBadgeActive: {
    backgroundColor: `${Colors.error}E6`,
  },
  statusBadgeEnded: {
    backgroundColor: `${Colors.slate900}D8`,
  },
  statusBadgeScheduled: {
    backgroundColor: `${Colors.primary}D8`,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
  },
  statusText: {
    color: Colors.white,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  audienceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.slate900}A8`,
  },
  audienceText: {
    color: Colors.white,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  audienceDot: {
    width: 6,
    height: 6,
    borderRadius: BorderRadius.full,
  },
  audienceDotLive: {
    backgroundColor: Colors.secondary,
  },
  audienceDotOffline: {
    backgroundColor: Colors.error,
  },
  heroContent: {
    position: 'absolute',
    right: Spacing.lg,
    bottom: Spacing.xl,
    left: Spacing.lg,
    gap: Spacing.base,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 8,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.white}1F`,
    borderWidth: 1,
    borderColor: `${Colors.white}33`,
  },
  chipText: {
    color: Colors.white,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  lotNumber: {
    color: `${Colors.white}C2`,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  title: {
    color: Colors.white,
    fontSize: FontSize.heading,
    lineHeight: 34,
    fontFamily: FontFamily.headlineBlack,
    fontWeight: '800',
  },
  sellerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  sellerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.white}F0`,
    ...Shadows.sm,
  },
  sellerLabel: {
    color: Colors.slate500,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
  },
  sellerValue: {
    color: Colors.onSurface,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  trustPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: `${Colors.secondary}26`,
    borderWidth: 1,
    borderColor: `${Colors.secondary}52`,
  },
  trustText: {
    color: Colors.white,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
});
