import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingBottom: 130,
  },
  header: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
    paddingHorizontal: Spacing.base,
    paddingBottom: Spacing.base,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    height: 56,
    paddingHorizontal: Spacing.base,
    ...Shadows.md,
    position: 'relative',
  },
  searchLogoOverlay: {
    position: 'absolute',
    left: Spacing.base,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    zIndex: 2,
  },
  searchLogoPlaceholder: {
    width: 108,
    height: 24,
    opacity: 0.5,
  },
  searchInput: {
    flex: 1,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyMedium,
    color: Colors.onSurface,
  },
  searchClearButton: {
    padding: 4,
  },
  searchActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  searchActionButton: {
    minWidth: 44,
    height: 40,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.sm,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primaryTintBorderFaint,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.sm,
  },
  profileActionButton: {
    backgroundColor: Colors.primaryTintSurface,
    borderColor: Colors.primaryTintBorder,
  },
  notificationActionButton: {
    backgroundColor: Colors.primaryTintSurface,
    borderColor: Colors.primaryTintBorder,
  },
  section: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.lg,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  sectionTitle: {
    fontSize: FontSize.subheading,
    fontFamily: FontFamily.bodyBold,
    color: Colors.onSurface,
  },
  categoriesRibbonContainer: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
    paddingVertical: Spacing.md,
  },
  categoriesScroll: {
    paddingHorizontal: Spacing.base,
    gap: Spacing.lg,
  },
  subcategoriesRibbonContainer: {
    backgroundColor: Colors.white,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
  },
  subcategoriesScroll: {
    paddingHorizontal: Spacing.base,
    gap: Spacing.sm,
  },
  subcategoryChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.slate50,
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  subcategoryChipActive: {
    backgroundColor: `${Colors.primary}1A`,
    borderColor: Colors.primary,
  },
  subcategoryChipText: {
    fontSize: 13,
    fontFamily: FontFamily.bodyMedium,
    color: Colors.slate600,
  },
  subcategoryChipTextActive: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
  },
  categoryItem: {
    alignItems: 'center',
    gap: Spacing.xs,
  },
  categoryIcon: {
    width: 56,
    height: 56,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.slate200,
    ...Shadows.sm,
  },
  categoryIconActive: {
    borderColor: Colors.primary,
    borderWidth: 2,
    backgroundColor: `${Colors.primary}0D`,
    ...Shadows.colored(Colors.primary),
  },
  categoryImage: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: Colors.slate200,
    backgroundColor: Colors.surfaceContainerLow,
    ...Shadows.sm,
  },
  categoryImageActive: {
    borderColor: Colors.primary,
    borderWidth: 2,
    ...Shadows.colored(Colors.primary),
  },
  categoryName: {
    fontSize: 11,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurface,
    textAlign: 'center',
    maxWidth: 72,
  },
  categoryNameActive: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: Spacing.xs,
  },
  productRow: {
    justifyContent: 'space-between',
  },
  productCardWrap: {
    width: '48.5%',
    marginBottom: Spacing.base,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.xl,
    minHeight: 220,
  },
  emptyText: {
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurfaceVariant,
    textAlign: 'center',
    marginTop: Spacing.sm,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xl,
    marginTop: Spacing.md,
  },
  retryText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
});
