import { StyleSheet } from 'react-native';
import { Colors } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.surface,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.slate100,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.onSurface,
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.onSurface,
  },
  sectionAction: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.primary,
  },
  addressOption: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderColor: Colors.slate200,
    borderRadius: 12,
    padding: 12,
  },
  addressOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.slate50,
  },
  addressTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.onSurface,
  },
  addressBody: {
    fontSize: 12,
    color: Colors.onSurfaceVariant,
    marginTop: 2,
  },
  addressEmpty: {
    fontSize: 13,
    color: Colors.onSurfaceVariant,
  },
  addAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.primary,
    paddingVertical: 10,
  },
  addAddressText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.primary,
  },
  couponRow: {
    flexDirection: 'row',
    gap: 8,
  },
  couponInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.slate200,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Colors.onSurface,
    backgroundColor: Colors.slate50,
  },
  couponButton: {
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: Colors.primary,
  },
  couponButtonText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  couponApplied: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.slate50,
    borderRadius: 12,
    padding: 12,
  },
  couponAppliedText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.onSurface,
  },
  couponRemoveText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.error,
  },
  summaryLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 13,
    color: Colors.onSurfaceVariant,
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.onSurface,
  },
  discountValue: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.error,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.slate200,
    paddingTop: 10,
    marginTop: 4,
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.onSurface,
  },
  totalValue: {
    fontSize: 17,
    fontWeight: '800',
    color: Colors.primary,
  },
  itemLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  itemTitle: {
    flex: 1,
    fontSize: 13,
    color: Colors.onSurface,
  },
  itemAmount: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.onSurface,
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 15,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    color: Colors.white,
    fontSize: 15,
    fontWeight: '700',
  },
  secureHint: {
    textAlign: 'center',
    fontSize: 11,
    color: Colors.onSurfaceVariant,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 24,
  },
});
