import { StyleSheet } from 'react-native';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.background,
    flex: 1,
  },
  content: {
    padding: Spacing.base,
    paddingBottom: 140,
  },
  center: {
    alignItems: 'center',
    backgroundColor: Colors.background,
    flex: 1,
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  centerTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.subheading,
    fontWeight: '700',
    marginTop: Spacing.base,
  },
  centerBody: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    marginTop: Spacing.sm,
    textAlign: 'center',
  },
  hero: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['3xl'],
    marginBottom: Spacing.base,
    padding: Spacing.xl,
    ...Shadows.md,
  },
  title: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.title,
    fontWeight: '800',
  },
  subtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 22,
    marginTop: Spacing.sm,
  },
  filterRow: {
    gap: Spacing.sm,
    marginBottom: Spacing.base,
    paddingRight: Spacing.base,
  },
  formTypeRow: {
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    paddingRight: Spacing.base,
  },
  inlineLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    fontWeight: '600',
  },
  chip: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  chipActive: {
    backgroundColor: Colors.primary,
  },
  chipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    fontWeight: '600',
  },
  chipTextActive: {
    color: Colors.white,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius['2xl'],
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.colored(Colors.primary),
  },
  addButtonText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  formCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['3xl'],
    gap: Spacing.sm,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  formTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.subheading,
    fontWeight: '700',
    marginBottom: Spacing.xs,
  },
  input: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.xl,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  rowInput: {
    flex: 1,
  },
  selectInput: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  selectInputText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  selectInputPlaceholder: {
    color: Colors.slate400,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  checkboxRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  checkboxLabel: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
  formActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  ghostButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    flex: 1,
    justifyContent: 'center',
    paddingVertical: Spacing.md,
  },
  ghostButtonText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.full,
    flex: 1,
    justifyContent: 'center',
    paddingVertical: Spacing.md,
  },
  primaryButtonText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  list: {
    gap: Spacing.base,
  },
  addressCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    gap: Spacing.sm,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  addressHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addressTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '700',
  },
  addressMeta: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.meta,
    marginTop: Spacing.xs,
  },
  typeBadge: {
    alignSelf: 'flex-start',
    marginTop: Spacing.xs,
    backgroundColor: `${Colors.primary}12`,
    borderColor: `${Colors.primary}28`,
    borderWidth: 1,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
  },
  typeBadgeText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    fontWeight: '600',
  },
  defaultBadge: {
    backgroundColor: Colors.secondaryContainer,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  defaultBadgeText: {
    color: Colors.secondary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    fontWeight: '600',
  },
  addressBody: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 22,
  },
  addressActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  inlineButton: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  inlineButtonText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    fontWeight: '600',
  },
  inlineButtonDanger: {
    backgroundColor: Colors.errorContainer,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  inlineButtonDangerText: {
    color: Colors.error,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    fontWeight: '600',
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['3xl'],
    gap: Spacing.sm,
    marginTop: Spacing.base,
    padding: Spacing.xl,
    ...Shadows.sm,
  },
  emptyTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.subheading,
    fontWeight: '700',
  },
  emptyBody: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 22,
    textAlign: 'center',
  },
  bottomSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: `${Colors.black}55`,
  },
  bottomSheetCard: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius['3xl'],
    borderTopRightRadius: BorderRadius['3xl'],
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.xl,
    maxHeight: '70%',
    ...Shadows.lg,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  bottomSheetTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.subheading,
    fontWeight: '700',
  },
  bottomSheetSearch: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.xl,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    marginBottom: Spacing.sm,
  },
  bottomSheetList: {
    maxHeight: 340,
  },
  bottomSheetItem: {
    borderBottomColor: Colors.slate100,
    borderBottomWidth: 1,
    paddingVertical: Spacing.md,
  },
  bottomSheetItemText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
});
