export enum AdRequestStatus {
  DRAFT = 'DRAFT',
  REQUESTED = 'REQUESTED',
  ADMIN_REVIEW = 'ADMIN_REVIEW',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}
