export enum AdminSettingKey {
  COMMISSION_DEFAULT_RATE = 'COMMISSION_DEFAULT_RATE',
  ESCROW_AUTO_CONFIRM_HOURS = 'ESCROW_AUTO_CONFIRM_HOURS',
  CARGO_MOCK_ENABLED = 'CARGO_MOCK_ENABLED',
  NOTIFICATION_TEMPLATE_OVERRIDES = 'NOTIFICATION_TEMPLATE_OVERRIDES',
  AD_SPONSORED_DENSITY = 'AD_SPONSORED_DENSITY',
  TRUST_GRACE_DAYS = 'TRUST_GRACE_DAYS',
  PRODUCT_IMAGE_UPLOAD_LIMITS = 'PRODUCT_IMAGE_UPLOAD_LIMITS',
  CONTENT_STUDIO = 'CONTENT_STUDIO',
}
