export enum BannerActionType {
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
  PRODUCTS = 'PRODUCTS',
  EXTERNAL_URL = 'EXTERNAL_URL',
  CAMPAIGNS = 'CAMPAIGNS',
  AUCTIONS = 'AUCTIONS',
  SEARCH = 'SEARCH',
  CUSTOM_ROUTE = 'CUSTOM_ROUTE',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
}



