export enum LedgerAccountType {
  BUYER_CASH = 'BUYER_CASH',
  SELLER_AVAILABLE = 'SELLER_AVAILABLE',
  SELLER_PENDING = 'SELLER_PENDING',
  ESCROW = 'ESCROW',
  PLATFORM_FEE = 'PLATFORM_FEE',
  PAYOUT_RESERVED = 'PAYOUT_RESERVED',
}
