export enum MobileBlockType {
  HERO_BANNER = 'HERO_BANNER',
  ENTRY_TILE = 'ENTRY_TILE',
  HOME_SECTION = 'HOME_SECTION',
  PROMO_BANNER = 'PROMO_BANNER',
  TRUST_BLOCK = 'TRUST_BLOCK',
  PRODUCT_CARD = 'PRODUCT_CARD',
  AUCTION_CARD = 'AUCTION_CARD',
  SURFACE_SLOT = 'SURFACE_SLOT',
}
