export enum NegotiationMessageType {
  USER_MESSAGE = 'USER_MESSAGE',
  PRICE_REQUEST = 'PRICE_REQUEST',
  OFFER = 'OFFER',
  COUNTER_OFFER = 'COUNTER_OFFER',
  SYSTEM = 'SYSTEM',
  VIOLATION_BLOCKED = 'VIOLATION_BLOCKED',
}
