export enum NegotiationStatus {
  OPEN = 'OPEN',
  NEGOTIATING = 'NEGOTIATING',
  OFFER_PENDING = 'OFFER_PENDING',
  ACCEPTED = 'ACCEPTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}
