export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ESCROW_HELD = 'ESCROW_HELD',
  PREPARING_SHIPMENT = 'PREPARING_SHIPMENT',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  ADMIN_REVIEW = 'ADMIN_REVIEW',
}
