export enum RestrictionType {
  WARNING = 'WARNING',
  ADS_CAMPAIGNS_LOCK = 'ADS_CAMPAIGNS_LOCK',
  PAYOUT_MANUAL_REVIEW = 'PAYOUT_MANUAL_REVIEW',
  SELLING_RESTRICTED = 'SELLING_RESTRICTED',
  MEMBERSHIP_CANCELLED = 'MEMBERSHIP_CANCELLED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
}
