import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.background,
    flex: 1,
  },
  center: {
    alignItems: 'center',
    backgroundColor: Colors.background,
    flex: 1,
    gap: Spacing.md,
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  centerText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  backAction: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  backActionText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  header: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderBottomColor: Colors.slate100,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: Spacing.md,
    paddingBottom: Spacing.md,
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.xxl,
    ...Shadows.sm,
  },
  headerButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  headerContent: {
    flex: 1,
  },
  title: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '700',
  },
  subtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: Spacing.xs,
  },
  statusRow: {
    backgroundColor: Colors.background,
    gap: Spacing.sm,
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
  },
  minimumHint: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
  },
  policyBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.error,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  policyBadgeLocked: {
    backgroundColor: Colors.errorContainer,
  },
  policyBadgeText: {
    color: Colors.error,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    padding: Spacing.base,
    paddingBottom: Spacing.xl,
  },
  emptyThread: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    gap: Spacing.sm,
    padding: Spacing.xl,
  },
  emptyTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '700',
  },
  emptyText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 20,
    textAlign: 'center',
  },

  // ─── Ürün bağlam kartı ─────────────────────────────────────
  productCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.slate100,
  },
  productCardImage: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.slate100,
  },
  productCardBody: {
    flex: 1,
    minWidth: 0,
  },
  productCardTitle: {
    fontSize: FontSize.meta,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurface,
  },
  productCardSubtitle: {
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
    color: Colors.slate500,
    marginTop: 1,
  },
  productCardLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  productCardLinkText: {
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodyMedium,
    color: Colors.primary,
  },

  // ─── Sabit teklif bandı ────────────────────────────────────
  offerBand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: `${Colors.primary}0D`,
    borderWidth: 1,
    borderColor: `${Colors.primary}33`,
  },
  offerBandInfo: {
    flex: 1,
  },
  offerBandLabel: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bodyMedium,
    color: Colors.slate500,
  },
  offerBandAmount: {
    fontSize: FontSize.subheading,
    fontFamily: FontFamily.bodyBold,
    color: Colors.onSurface,
  },
  offerBandActions: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  offerBandAccept: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  offerBandAcceptText: {
    color: Colors.white,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
  },
  offerBandReject: {
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.error,
  },
  offerBandRejectText: {
    color: Colors.error,
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
  },
  offerBandWaiting: {
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodyMedium,
    color: Colors.slate400,
  },
});
