import { Platform, StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  center: {
    alignItems: 'center',
    backgroundColor: Colors.background,
    flex: 1,
    gap: Spacing.md,
    justifyContent: 'center',
  },
  errorText: {
    color: Colors.error,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.bodyXl,
  },
  scrollView: {
    paddingBottom: Platform.OS === 'ios' ? 24 : Spacing.lg,
  },

  topBar: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderBottomColor: Colors.slate100,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingTop: Platform.OS === 'ios' ? 52 : Spacing.lg,
    paddingBottom: Spacing.sm,
    ...Shadows.sm,
  },
  topBarIconButton: {
    alignItems: 'center',
    borderRadius: BorderRadius.full,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  topBarTitle: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
    marginHorizontal: Spacing.sm,
    textAlign: 'center',
  },
  topBarActions: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },

  heroImageContainer: {
    backgroundColor: Colors.surfaceContainerLow,
    borderBottomLeftRadius: BorderRadius['3xl'],
    borderBottomRightRadius: BorderRadius['3xl'],
    marginBottom: Spacing.sm,
    overflow: 'hidden',
    position: 'relative',
    ...Shadows.md,
  },
  heroImage: {
    height: 320,
    width: '100%',
  },
  heroSideBadges: {
    gap: Spacing.xs,
    left: Spacing.sm,
    position: 'absolute',
    top: Spacing.xl,
  },
  heroSideBadgePill: {
    alignItems: 'center',
    backgroundColor: Colors.transparent,
    borderColor: Colors.transparent,
    borderRadius: 0,
    borderWidth: 0,
    height: 34,
    justifyContent: 'center',
    width: 68,
  },
  heroSideBadgeImage: {
    height: 24,
    width: 60,
  },
  content: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.xl,
  },
  summaryBlock: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.lg,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  sellerKicker: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    fontWeight: '600',
    letterSpacing: 0.8,
    marginBottom: Spacing.xs,
  },
  title: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.heading,
    fontWeight: '900',
    lineHeight: 34,
    marginBottom: Spacing.sm,
  },
  summaryText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    lineHeight: 22,
  },
  summaryBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.base,
  },
  summaryBadgePill: {
    alignItems: 'center',
    backgroundColor: Colors.transparent,
    borderColor: Colors.transparent,
    borderRadius: 0,
    borderWidth: 0,
    height: 26,
    justifyContent: 'center',
    paddingHorizontal: 0,
  },
  summaryBadgeImage: {
    height: 26,
    width: 74,
  },
  brandCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    ...Shadows.sm,
  },
  brandCardTextWrap: {
    flex: 1,
    marginRight: Spacing.sm,
  },
  brandCardLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    marginBottom: 2,
  },
  brandCardValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
    fontWeight: '700',
  },
  geoInfoCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.lg,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  geoInfoHeader: {
    marginBottom: Spacing.xs,
  },
  geoInfoTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  geoInfoTitleIconWrap: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}14`,
    borderRadius: BorderRadius.md,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  geoInfoTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
    fontWeight: '700',
    marginBottom: 0,
  },
  geoTypeBadgeRow: {
    gap: Spacing.xs,
    paddingTop: Spacing.sm,
  },
  geoTypeBadgeChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: `${Colors.primary}10`,
    borderColor: `${Colors.primary}26`,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    minHeight: 28,
    paddingHorizontal: Spacing.sm,
  },
  geoTypeBadgeLogo: {
    height: 18,
    width: 18,
  },
  geoTypeBadgeLabel: {
    color: Colors.primaryContainer,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    fontWeight: '700',
  },
  geoInfoRow: {
    borderTopColor: Colors.slate100,
    borderTopWidth: 1,
    paddingVertical: Spacing.sm,
  },
  geoInfoLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    marginBottom: Spacing.xs,
  },
  geoInfoValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  reviewInfoCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.lg,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  reviewInfoTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
    fontWeight: '700',
    marginBottom: Spacing.xs,
  },
  reviewScoreText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  reviewEmptySummaryText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    marginTop: Spacing.xs,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    marginTop: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  reviewInfoRow: {
    borderTopColor: Colors.slate100,
    borderTopWidth: 1,
    paddingVertical: Spacing.sm,
  },
  reviewInfoLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    marginBottom: Spacing.xs,
  },
  reviewInfoValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  sellerInfoCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    ...Shadows.sm,
  },
  sellerInfoIconWrap: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}10`,
    borderRadius: BorderRadius.md,
    height: 34,
    justifyContent: 'center',
    marginRight: Spacing.sm,
    width: 34,
  },
  sellerInfoTextWrap: {
    flex: 1,
  },
  sellerInfoLabel: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    marginBottom: 2,
  },
  sellerInfoName: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
    fontWeight: '700',
  },
  sellerInfoCtaWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
    marginLeft: Spacing.sm,
  },
  sellerInfoCtaText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
  },
  reviewModalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    flex: 1,
    justifyContent: 'center',
    padding: Spacing.base,
  },
  reviewModalCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    maxHeight: '75%',
    padding: Spacing.base,
    width: '100%',
  },
  reviewModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  reviewModalTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
    fontWeight: '700',
  },
  reviewModalCloseButton: {
    alignItems: 'center',
    borderRadius: BorderRadius.full,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  reviewModalItem: {
    borderTopColor: Colors.slate100,
    borderTopWidth: 1,
    paddingVertical: Spacing.sm,
  },
  reviewModalStarsRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  reviewModalComment: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 20,
  },
  reviewModalEmpty: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingVertical: Spacing.base,
  },
  badgeInfoBody: {
    alignItems: 'center',
    paddingVertical: Spacing.sm,
  },
  badgeInfoImage: {
    height: 56,
    marginBottom: Spacing.sm,
    width: 140,
  },
  badgeInfoDescription: {
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 21,
    textAlign: 'center',
  },

  purchaseCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  purchasePriceRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    marginBottom: Spacing.sm,
  },
  purchasePrice: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheading,
    fontWeight: '600',
  },
  purchaseUnitText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.sm,
    marginLeft: Spacing.sm,
    marginBottom: 3,
  },
  primaryActionButton: {
    alignItems: 'center',
    backgroundColor: Colors.primaryContainer,
    borderRadius: BorderRadius.lg,
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    marginBottom: Spacing.sm,
    minHeight: 44,
    paddingHorizontal: Spacing.base,
    ...Shadows.colored(Colors.primaryContainer),
  },
  primaryActionText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  inlineQuantityStepper: {
    alignItems: 'center',
    backgroundColor: Colors.primaryContainer,
    borderRadius: BorderRadius.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    padding: Spacing.xs,
    ...Shadows.colored(Colors.primaryContainer),
  },
  inlineQuantityButton: {
    alignItems: 'center',
    backgroundColor: `${Colors.white}22`,
    borderRadius: BorderRadius.md,
    height: 32,
    justifyContent: 'center',
    width: 36,
  },
  inlineQuantityValue: {
    color: Colors.white,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '600',
    minWidth: 86,
    textAlign: 'center',
  },
  stickyCartCtaWrap: {
    bottom: Platform.OS === 'ios' ? Spacing.lg : Spacing.base,
    left: Spacing.base,
    position: 'absolute',
    right: Spacing.base,
    zIndex: 60,
  },
  stickyCartCtaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  stickyCartUtilityButton: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
    ...Shadows.sm,
  },
  stickyCartCtaButton: {
    alignItems: 'center',
    backgroundColor: Colors.primaryContainer,
    borderColor: Colors.primaryContainer,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: Spacing.base,
    ...Shadows.sm,
  },
  stickyCartCtaText: {
    color: Colors.white,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
  stickyQuantityStepper: {
    alignItems: 'center',
    backgroundColor: Colors.primaryContainer,
    borderRadius: BorderRadius.lg,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    padding: Spacing.xs,
    ...Shadows.colored(Colors.primaryContainer),
  },
  stickyQuantityButton: {
    alignItems: 'center',
    backgroundColor: `${Colors.white}22`,
    borderRadius: BorderRadius.md,
    height: 32,
    justifyContent: 'center',
    width: 36,
  },
  stickyQuantityValue: {
    color: Colors.white,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
    minWidth: 86,
    textAlign: 'center',
  },
  variantSectionCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  variantGroupWrap: {
    marginBottom: Spacing.base,
  },
  variantGroupTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
    marginBottom: Spacing.sm,
  },
  colorVariantRow: {
    gap: Spacing.sm,
    paddingRight: Spacing.xs,
  },
  colorVariantCard: {
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    overflow: 'hidden',
    width: 98,
  },
  colorVariantCardActive: {
    borderColor: Colors.primaryContainer,
  },
  colorVariantImageWrap: {
    backgroundColor: Colors.surfaceContainerLow,
    height: 74,
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
  },
  colorVariantImage: {
    height: '100%',
    width: '100%',
  },
  colorVariantSwatchFallback: {
    borderRadius: BorderRadius.md,
    height: 38,
    marginHorizontal: Spacing.base,
  },
  colorVariantLabel: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    textAlign: 'center',
  },
  colorVariantLabelActive: {
    color: Colors.primaryContainer,
  },
  variantOutOfStockOverlay: {
    alignItems: 'center',
    backgroundColor: `${Colors.slate900}73`,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  variantOutOfStockText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    fontWeight: '700',
  },
  sizeVariantWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  sizeVariantChip: {
    alignItems: 'center',
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 56,
    paddingHorizontal: Spacing.sm,
  },
  sizeVariantChipActive: {
    borderColor: Colors.primaryContainer,
  },
  sizeVariantChipText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    fontWeight: '600',
  },
  sizeVariantChipTextActive: {
    color: Colors.primaryContainer,
  },
  variantOptionDisabled: {
    opacity: 0.48,
  },
  variantOptionLabelDisabled: {
    color: Colors.slate500,
  },
  tabsWrap: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.base,
    position: 'relative',
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.sm,
    ...Shadows.sm,
  },
  tabsRow: {
    alignItems: 'center',
    gap: Spacing.base,
    paddingRight: Spacing.base,
  },
  tabButton: {
    justifyContent: 'center',
    minHeight: 28,
    paddingBottom: Spacing.xs,
    paddingTop: Spacing.xs,
  },
  tabButtonText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '600',
    lineHeight: 16,
  },
  tabButtonTextActive: {
    color: Colors.primaryContainer,
  },
  tabUnderline: {
    backgroundColor: Colors.transparent,
    borderRadius: BorderRadius.full,
    height: 2,
    marginTop: Spacing.xs,
    width: '100%',
  },
  tabUnderlineActive: {
    backgroundColor: Colors.primaryContainer,
  },
  tabsScrollHint: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.full,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    top: Spacing.base,
    width: 20,
  },
  tabsScrollHintRight: {
    right: Spacing.sm,
  },
  tabsScrollHintLeft: {
    left: Spacing.sm,
  },
  tabAnimatedWrap: {
    borderTopColor: Colors.slate100,
    borderTopWidth: 1,
    marginTop: Spacing.xs,
  },

  tabContentCard: {
    paddingTop: Spacing.base,
    paddingHorizontal: Spacing.xs,
    paddingBottom: Spacing.xs,
  },
  tabContentTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
    marginBottom: Spacing.sm,
  },
  tabContentText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    lineHeight: 22,
  },
  detailRow: {
    borderBottomColor: Colors.slate100,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.sm,
  },
  detailLabel: {
    color: Colors.onSurfaceVariant,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    marginRight: Spacing.base,
  },
  detailValue: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    textAlign: 'right',
  },

  metaCardsWrap: {
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  metaCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  metaIconBadge: {
    alignItems: 'center',
    backgroundColor: `${Colors.secondary}14`,
    borderRadius: BorderRadius.md,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  metaTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
    marginBottom: 2,
  },
  metaValue: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },

  recommendedSection: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.xl,
    paddingTop: Spacing.base,
    ...Shadows.sm,
  },
  recommendedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingBottom: Spacing.base,
  },
  recommendedGridItem: {
    marginBottom: Spacing.sm,
    width: '48.5%',
  },
  flyToCartImage: {
    borderColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 2,
    height: 72,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 72,
    zIndex: 999,
    ...Shadows.md,
  },
});
