import { StyleSheet, Platform } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, Shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  tabBar: {
    backgroundColor: `${Colors.white}F7`,
    borderTopColor: Colors.slate200,
    borderTopWidth: 1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: Platform.OS === 'ios' ? 26 : Spacing.sm,
    paddingTop: Spacing.md,
    height: Platform.OS === 'ios' ? 92 : 70,
    position: 'absolute',
    ...Shadows.tabBar,
  },
  tabBarItem: {
    paddingVertical: 2,
    marginBottom: 5,
  },
  tabBarBackground: {
    flex: 1,
  },
  tabBarLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    letterSpacing: 0.2,
    marginTop: 3,
  },
  header: {
    backgroundColor: Colors.white,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
  },
  headerOnBackground: {
    backgroundColor: Colors.background,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
  },
  headerTitle: {
    fontFamily: FontFamily.headline,
    fontWeight: '700',
    fontSize: FontSize.subheading,
    color: Colors.primary,
  },
  headerGoatIcon: {
    width: 34,
    height: 34,
  },
  headerLeftContainer: {
    marginLeft: Spacing.sm,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginRight: Spacing.sm,
  },
  headerActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: `${Colors.primary}12`,
    paddingHorizontal: Spacing.md,
    paddingVertical: 7,
    borderRadius: 999,
    marginLeft: Spacing.sm,
    borderWidth: 1,
    borderColor: `${Colors.primary}1A`,
  },
  headerActionButtonCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: `${Colors.primary}12`,
    borderWidth: 1,
    borderColor: `${Colors.primary}2A`,
    ...Shadows.md,
  },
  headerActionText: {
    color: Colors.primary,
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
  },
  headerDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.slate200,
    marginHorizontal: 2,
  },
  headerIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: `${Colors.primary}10`,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: `${Colors.primary}2A`,
    ...Shadows.sm,
  },
  auctionIcon: {
    width: 24,
    height: 24,
  },
  auctionIconActive: {
    opacity: 1,
    tintColor: Colors.auctionGreen,
  },
  auctionIconInactive: {
    opacity: 0.6,
    tintColor: Colors.auctionGreen,
  },
  auctionLabelActive: {
    color: Colors.auctionGreen,
    opacity: 1,
  },
  auctionLabelInactive: {
    color: Colors.auctionGreen,
    opacity: 0.6,
  },
  cartBadge: {
    position: 'absolute',
    top: -6,
    right: -8,
    backgroundColor: Colors.accent,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.white,
    paddingHorizontal: 2,
  },
  cartBadgeText: {
    color: Colors.white,
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  floatingCartButton: {
    position: 'absolute',
    top: -29, // tab sekmesinden ~5px yukarıda görünsün
    right: 5, // sağdan 5px
    backgroundColor: Colors.primary,
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    ...Shadows.colored(Colors.primary),
  },
});
