import { StyleSheet } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, BorderRadius, Shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  sellerScrollContent: {
    paddingBottom: Spacing.xxxl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.base,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.slate200,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.sm,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.subheading,
    color: Colors.onSurface,
  },
  headerSpacer: {
    width: 40,
  },
  headerDraftButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 40,
    height: 34,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primaryTintSurface,
    borderWidth: 1,
    borderColor: `${Colors.primary}30`,
    justifyContent: 'center',
  },
  headerDraftButtonText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    color: Colors.primary,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    backgroundColor: `${Colors.primary}0D`,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: `${Colors.primary}38`,
    gap: Spacing.md,
    ...Shadows.sm,
  },
  infoBannerText: {
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    color: Colors.primaryContainer,
    lineHeight: 20,
  },
  sellerHeroCard: {
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.lg,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: `${Colors.primary}24`,
    ...Shadows.md,
  },
  sellerHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  sellerHeroBadge: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    letterSpacing: 0.7,
  },
  sellerHeroCountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  sellerHeroCountText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  sellerHeroTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
    marginBottom: Spacing.xs,
  },
  sellerHeroSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    lineHeight: 18,
  },
  typeSwitchRow: {
    flexDirection: 'row',
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    gap: Spacing.sm,
  },
  typeSwitchOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  typeSwitchOptionActive: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  typeSwitchText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  typeSwitchTextActive: {
    color: Colors.primary,
  },
  formCard: {
    marginHorizontal: Spacing.base,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: `${Colors.primary}20`,
    ...Shadows.lg,
  },
  sellerFormCard: {
    marginHorizontal: Spacing.base,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.slate100,
    ...Shadows.md,
  },
  inputGroup: {
    marginBottom: Spacing.lg,
  },
  inputLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    color: Colors.slate600,
    marginBottom: Spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    color: Colors.onSurface,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  textareaInput: {
    minHeight: 104,
  },
  inlineInputRow: {
    flexDirection: 'row',
    gap: Spacing.base,
  },
  inlineInputBlock: {
    flex: 1,
  },
  categorySelector: {
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categorySelectorLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categorySelectorMediaWrap: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.full,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  categorySelectorMediaImage: {
    width: '100%',
    height: '100%',
  },
  categorySelectorIconBadge: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 14,
    height: 14,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.slate200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categorySelectorText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  categorySelectorPlaceholder: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  agreementRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: Spacing.base,
    marginTop: Spacing.lg,
    gap: Spacing.md,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    borderColor: Colors.outline,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  agreementText: {
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    color: Colors.slate600,
    lineHeight: 20,
  },
  submitButton: {
    flexDirection: 'row',
    marginHorizontal: Spacing.base,
    marginTop: Spacing.xl,
    marginBottom: Spacing.lg,
    backgroundColor: Colors.secondary,
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.base,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    ...Shadows.colored(Colors.secondary),
  },
  submitButtonDisabled: {
    backgroundColor: Colors.slate300,
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyXl,
    color: Colors.white,
  },
  sellerListCard: {
    marginHorizontal: Spacing.base,
    marginTop: Spacing.sm,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: Colors.slate100,
    ...Shadows.sm,
  },
  sellerListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  sellerListTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
    paddingVertical: Spacing.sm,
  },
  productRowInfo: {
    flex: 1,
    paddingRight: Spacing.base,
  },
  productRowTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  productRowSub: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  statusPill: {
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  statusPillText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
  },
  emptyProducts: {
    alignItems: 'center',
    paddingVertical: Spacing.lg,
  },
  emptyProductsText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
  categoryModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  categoryModalSheet: {
    position: 'absolute',
    left: Spacing.base,
    right: Spacing.base,
    bottom: Spacing.base,
    maxHeight: '72%',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.base,
    ...Shadows.lg,
  },
  categoryModalHandle: {
    width: 48,
    height: 4,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.slate200,
    alignSelf: 'center',
    marginBottom: Spacing.sm,
  },
  categoryModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  categoryModalTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.bodyXl,
  },
  categoryModalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.surfaceContainerLow,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categorySearchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  categorySearchInput: {
    flex: 1,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingVertical: Spacing.sm,
  },
  rootCategoryRow: {
    gap: Spacing.sm,
    paddingBottom: Spacing.sm,
  },
  rootCategoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  rootCategoryChipSelected: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  rootCategoryChipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  rootCategoryChipTextSelected: {
    color: Colors.primary,
  },
  subcategoryTitle: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    marginBottom: Spacing.xs,
    marginTop: 2,
  },
  categoryListContent: {
    paddingBottom: Spacing.sm,
  },
  categoryListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.slate100,
    backgroundColor: Colors.surfaceContainerLowest,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  categoryListItemSelected: {
    borderColor: Colors.primary,
    backgroundColor: `${Colors.primary}0D`,
  },
  categoryListItemLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categoryListMediaWrap: {
    width: 30,
    height: 30,
    borderRadius: BorderRadius.full,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: Colors.slate200,
  },
  categoryListMediaImage: {
    width: '100%',
    height: '100%',
  },
  categoryListIconBadge: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 14,
    height: 14,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.slate200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryListItemText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    flex: 1,
    paddingRight: Spacing.sm,
  },
  categoryListItemTextSelected: {
    color: Colors.primary,
  },
  categoryEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xl,
  },
  categoryEmptyStateText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
  alreadySellerCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.xxl,
    gap: Spacing.base,
  },
  alreadySellerText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheading,
    color: Colors.onSurface,
    textAlign: 'center',
  },
  backBtn: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    marginTop: Spacing.base,
  },
  backBtnText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: Colors.white,
  },
});
