import { StyleSheet } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, BorderRadius, Shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  bottomSpacer: { height: 100 },
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    padding: Spacing.base,
  },
  heroCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}1F`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.md,
  },
  heroBadge: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    letterSpacing: 0.7,
    marginBottom: Spacing.xs,
  },
  heroTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
    marginBottom: Spacing.xs,
  },
  heroSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginBottom: Spacing.base,
  },
  searchInputWrap: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.base,
  },
  searchInput: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingVertical: Spacing.md,
  },
  sortRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  sortChip: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  sortChipActive: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  sortChipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  sortChipTextActive: {
    color: Colors.primary,
  },
  sectionTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.subheading,
    marginBottom: Spacing.sm,
  },
  featuredCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: Spacing.sm,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  featuredImage: {
    backgroundColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    height: 56,
    width: 56,
  },
  featuredIconWrap: {
    alignItems: 'center',
    borderRadius: BorderRadius.lg,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  featuredContent: {
    flex: 1,
    marginHorizontal: Spacing.base,
  },
  featuredTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
    marginBottom: 2,
  },
  featuredCount: {
    color: Colors.slate500,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  emptyText: {
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurfaceVariant,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xl,
    marginTop: Spacing.sm,
  },
  retryText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  card: {
    width: '47.5%',
    flexGrow: 1,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.base,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.slate100,
    ...Shadows.sm,
  },
  iconBox: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  categoryImage: {
    width: 72,
    height: 72,
    borderRadius: BorderRadius.xl,
    marginBottom: Spacing.md,
    backgroundColor: Colors.slate100,
  },
  cardName: {
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurface,
    textAlign: 'center',
    marginBottom: Spacing.xs,
  },
  cardCount: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.body,
    color: Colors.slate400,
  },
  emptySearchState: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    gap: Spacing.xs,
    justifyContent: 'center',
    marginTop: Spacing.base,
    minHeight: 120,
    paddingHorizontal: Spacing.base,
  },
  emptySearchText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
});
