import { StyleSheet, Platform } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, BorderRadius, Shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingHorizontal: Spacing.base,
    paddingBottom: Platform.OS === 'ios' ? 140 : 110,
    gap: Spacing.lg,
  },
  headerSection: {
    paddingTop: Spacing.base,
    paddingBottom: Spacing.sm,
    gap: Spacing.xs,
  },
  headerEyebrow: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  headerTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleLg,
    fontWeight: '800',
    marginTop: 2,
  },
  headerSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
    marginTop: Spacing.xs,
  },
  searchBarWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.slate200,
    paddingHorizontal: Spacing.base,
    marginTop: Spacing.md,
    ...Shadows.md,
  },
  searchIcon: {
    marginRight: Spacing.sm,
  },
  searchInput: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    paddingVertical: Platform.OS === 'ios' ? Spacing.md : Spacing.sm,
  },
  searchClearButton: {
    padding: Spacing.xs,
  },
  sortSection: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  sortButton: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1.5,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    ...Shadows.sm,
  },
  sortButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    ...Shadows.colored(Colors.primary),
  },
  sortButtonText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  sortButtonTextActive: {
    color: Colors.white,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.xs,
  },
  sectionTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headline,
    fontSize: FontSize.subheading,
    fontWeight: '700',
  },
  featuredList: {
    gap: Spacing.md,
  },
  featuredCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: Colors.slate100,
    ...Shadows.md,
  },
  featuredImage: {
    backgroundColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    height: 56,
    width: 56,
  },
  featuredIconWrap: {
    alignItems: 'center',
    borderRadius: BorderRadius.lg,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  featuredContent: {
    flex: 1,
    marginLeft: Spacing.base,
    gap: Spacing.xs,
  },
  featuredName: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
  },
  featuredBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
  },
  featuredBadgeText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  gridCard: {
    width: '47.5%',
    flexGrow: 1,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.base,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.slate100,
    position: 'relative',
    ...Shadows.sm,
  },
  gridCardBadge: {
    position: 'absolute',
    top: Spacing.sm,
    right: Spacing.sm,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
  },
  gridCardBadgeText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
  },
  gridImage: {
    width: 64,
    height: 64,
    borderRadius: BorderRadius.xl,
    marginBottom: Spacing.sm,
    marginTop: Spacing.sm,
    backgroundColor: Colors.slate100,
  },
  gridIconWrap: {
    width: 64,
    height: 64,
    borderRadius: BorderRadius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.sm,
    marginTop: Spacing.sm,
  },
  gridCardName: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  emptyText: {
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurfaceVariant,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xl,
    marginTop: Spacing.sm,
  },
  retryText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  emptySearchState: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    gap: Spacing.xs,
    justifyContent: 'center',
    marginTop: Spacing.base,
    minHeight: 120,
    paddingHorizontal: Spacing.base,
  },
  emptySearchText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
});
