import { StyleSheet } from 'react-native';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    padding: Spacing.base,
    paddingBottom: Spacing.xxxl,
    gap: Spacing.xl,
  },
  heroCard: {
    borderRadius: BorderRadius['3xl'],
    padding: Spacing.lg,
    backgroundColor: Colors.surfaceContainerLowest,
    borderWidth: 0,
    ...Shadows.md,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  headerLogo: {
    width: 130,
    height: 28,
  },
  headerNotificationButton: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: Colors.surfaceContainer,
  },
  searchInput: {
    flex: 1,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyXl,
    paddingVertical: Spacing.xs,
  },
  searchClearButton: {
    padding: Spacing.xs,
  },
  filterScroll: {
    marginHorizontal: -Spacing.base,
  },
  filterScrollContent: {
    paddingHorizontal: Spacing.base,
    gap: Spacing.sm,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    borderWidth: 1.5,
    borderColor: Colors.outlineVariant,
    backgroundColor: Colors.surfaceContainerLowest,
  },
  filterChipActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryFixed,
  },
  filterChipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
  },
  filterChipTextActive: {
    color: Colors.primaryContainer,
  },
  section: {
    gap: Spacing.base,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headline,
    fontSize: FontSize.subheading,
    fontWeight: '700',
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  sectionActionText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
  },
  hintCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.base,
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.xl,
    borderWidth: 0,
    elevation: 0,
  },
  hintText: {
    flex: 1,
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.meta,
    lineHeight: 18,
  },
  categoryScroll: {
    marginHorizontal: -Spacing.base,
  },
  categoryScrollContent: {
    paddingHorizontal: Spacing.base,
    gap: Spacing.sm,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    borderWidth: 0,
    shadowColor: 'rgba(0,0,0,0.02)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryChipText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
  },
  carouselScroll: {
    marginHorizontal: -Spacing.base,
  },
  carouselScrollContent: {
    paddingHorizontal: Spacing.base,
    gap: Spacing.base,
  },
  productCardWrap: {
    width: 160,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: Spacing.base,
  },
  productGridCardWrap: {
    width: '47.5%',
  },
  auctionCard: {
    flexDirection: 'row',
    gap: Spacing.base,
    padding: Spacing.base,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.surfaceContainerLowest,
    borderWidth: 0,
    ...Shadows.sm,
  },
  auctionImage: {
    width: 90,
    height: 90,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceContainer,
  },
  auctionBody: {
    flex: 1,
    gap: Spacing.xs,
    justifyContent: 'space-between',
  },
  auctionHeader: {
    gap: 2,
  },
  auctionTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
  },
  auctionMeta: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.meta,
  },
  auctionPriceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: Spacing.xs,
  },
  auctionPriceLabel: {
    fontSize: FontSize.caption,
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
  },
  auctionPrice: {
    color: Colors.auctionGreen,
    fontFamily: FontFamily.price,
    fontWeight: '700',
    fontSize: FontSize.subheading,
  },
  auctionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  reserveBadge: {
    flexShrink: 1,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.md,
  },
  reserveBadgeText: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bodyBold,
    fontWeight: '700',
  },
  blogScroll: {
    gap: Spacing.base,
    paddingRight: Spacing.base,
  },
  emptyCard: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    backgroundColor: Colors.surfaceContainerLow,
    gap: Spacing.sm,
  },
  emptyTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
  },
  emptyBody: {
    textAlign: 'center',
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
});
