import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.background,
    flex: 1,
  },
  scrollContent: {
    gap: Spacing.base,
    padding: Spacing.base,
    paddingBottom: Spacing.xxxl,
  },
  center: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: Spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: Spacing.xs,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
    ...Shadows.sm,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.subheading,
    color: Colors.onSurface,
    fontWeight: '700',
  },
  headerSpacer: {
    width: 40,
  },
  descriptionContainer: {
    marginBottom: Spacing.xs,
  },
  subtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
    gap: Spacing.xs,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  summaryLabel: {
    color: Colors.slate500,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  summaryValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headline,
    fontSize: FontSize.titleSm,
    fontWeight: '700',
  },
  sectionTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headline,
    fontSize: FontSize.subheading,
    fontWeight: '700',
  },
  emptyCard: {
    backgroundColor: Colors.slate50,
    borderRadius: BorderRadius.xl,
    padding: Spacing.base,
  },
  emptyText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    lineHeight: 20,
  },
  tabContainer: {
    backgroundColor: Colors.slate100,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    marginTop: Spacing.sm,
    padding: Spacing.xs,
  },
  tabSegment: {
    alignItems: 'center',
    borderRadius: BorderRadius.full,
    flex: 1,
    paddingVertical: Spacing.sm,
  },
  tabSegmentActive: {
    backgroundColor: Colors.white,
    ...Shadows.sm,
  },
  tabText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  tabTextActive: {
    color: Colors.primary,
  },
  tabContentContainer: {
    gap: Spacing.base,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDismissArea: {
    flex: 1,
  },
  modalContainer: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius['3xl'],
    borderTopRightRadius: BorderRadius['3xl'],
    padding: Spacing.xl,
    paddingBottom: Spacing.xxl,
    ...Shadows.lg,
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    height: 4,
    marginBottom: Spacing.lg,
    width: 40,
  },
  modalTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.title,
    fontWeight: '800',
    marginBottom: Spacing.xs,
  },
  modalDescription: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    lineHeight: 22,
    marginBottom: Spacing.md,
  },
  modalDivider: {
    backgroundColor: Colors.slate100,
    height: 1,
    marginVertical: Spacing.md,
  },
  modalDetailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.sm,
  },
  modalDetailLabel: {
    color: Colors.slate500,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  modalDetailValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyXl,
    fontWeight: '600',
  },
  modalWalletBox: {
    alignItems: 'center',
    backgroundColor: Colors.slate50,
    borderRadius: BorderRadius.xl,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: Spacing.base,
    marginTop: Spacing.sm,
  },
  modalWalletLabel: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.body,
  },
  modalWalletValue: {
    color: Colors.primary,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.bodyXl,
    fontWeight: '700',
  },
  modalWarningBox: {
    alignItems: 'center',
    backgroundColor: Colors.errorContainer,
    borderRadius: BorderRadius.xl,
    flexDirection: 'row',
    gap: Spacing.sm,
    padding: Spacing.base,
    marginTop: Spacing.md,
  },
  modalWarningText: {
    color: Colors.onErrorContainer,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    flex: 1,
  },
  modalActions: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginTop: Spacing.xl,
  },
  modalCancelButton: {
    alignItems: 'center',
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  modalCancelButtonText: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  modalSubmitButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    flex: 2,
    height: 48,
    justifyContent: 'center',
  },
  modalSubmitButtonDisabled: {
    backgroundColor: Colors.slate400,
  },
  modalSubmitButtonText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
});
