import { StyleSheet } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, BorderRadius, Shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.base,
    paddingTop: 60,
    paddingBottom: Spacing.base,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.subheading,
    color: Colors.onSurface,
  },
  headerSpacer: {
    width: 40,
  },
  sectionTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    color: Colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.xl,
    marginBottom: Spacing.sm,
  },
  sectionTitleDanger: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    color: Colors.error,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.xxl,
    marginBottom: Spacing.sm,
  },
  card: {
    marginHorizontal: Spacing.base,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    ...Shadows.md,
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  consentInfo: {
    flex: 1,
  },
  consentTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
    color: Colors.onSurface,
  },
  consentDesc: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    color: Colors.slate500,
    marginTop: 2,
    lineHeight: 16,
  },
  consentRequired: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.xs,
    color: Colors.primary,
    marginTop: Spacing.xs,
    fontStyle: 'italic',
  },
  divider: {
    height: 1,
    backgroundColor: Colors.surfaceContainerHigh,
    marginVertical: Spacing.md,
  },
  dangerCard: {
    marginHorizontal: Spacing.base,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: `${Colors.error}20`,
    ...Shadows.sm,
  },
  dangerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.base,
    gap: Spacing.sm,
  },
  dangerButtonText: {
    flex: 1,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
    color: Colors.error,
  },
  deleteSection: {
    padding: Spacing.base,
    borderTopWidth: 1,
    borderTopColor: `${Colors.error}15`,
    backgroundColor: `${Colors.error}05`,
  },
  deleteWarning: {
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
    color: Colors.slate600,
    lineHeight: 20,
    marginBottom: Spacing.md,
  },
  deleteInput: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    color: Colors.onSurface,
    borderWidth: 1,
    borderColor: Colors.error,
    marginBottom: Spacing.md,
  },
  deleteConfirmBtn: {
    backgroundColor: Colors.error,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.md,
    alignItems: 'center',
  },
  deleteConfirmBtnDisabled: {
    backgroundColor: Colors.slate300,
  },
  deleteConfirmText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: Colors.white,
  },
  bottomSpacer: {
    height: 100,
  },
});
