/**
 * Merkezi API Yanıt Kodları
 * CONVENTION #12: Tüm backend yanıtları { code, message, ...data } formatında olmalıdır.
 * Yeni endpoint yazıldığında ilgili kodu BURAYA eklenmek ZORUNLUDUR.
 */

// ==========================================
// Auth
// ==========================================
export const AUTH = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  PROFILE_FETCHED: 'PROFILE_FETCHED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  RESET_EMAIL_SENT: 'RESET_EMAIL_SENT',
  PASSWORD_RESET: 'PASSWORD_RESET',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  VERIFICATION_TOKEN_EXPIRED: 'VERIFICATION_TOKEN_EXPIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_DELETED_LOGIN: 'ACCOUNT_DELETED_LOGIN', // BIZ-04: Soft-deleted user login rejection
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED', // T-1-05: Refresh token reuse → all sessions revoked
} as const;

// ==========================================
// User / Profile
// ==========================================
export const USER = {
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  ADDRESS_LIST_FETCHED: 'ADDRESS_LIST_FETCHED',
  ADDRESS_CREATED: 'ADDRESS_CREATED',
  ADDRESS_UPDATED: 'ADDRESS_UPDATED',
  ADDRESS_DELETED: 'ADDRESS_DELETED',
  ADDRESS_DEFAULT_SET: 'ADDRESS_DEFAULT_SET',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_REACTIVATED: 'ACCOUNT_REACTIVATED',
  ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',
  ACCOUNT_DELETE_BLOCKED: 'ACCOUNT_DELETE_BLOCKED',
  REACTIVATION_FAILED: 'REACTIVATION_FAILED',
  GRACE_PERIOD_EXPIRED: 'GRACE_PERIOD_EXPIRED',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
} as const;

// ==========================================
// Seller
// ==========================================
export const SELLER = {
  BECOME_SELLER_SUCCESS: 'BECOME_SELLER_SUCCESS',
  SELLER_APPLICATION_PENDING: 'SELLER_APPLICATION_PENDING',
  ALREADY_SELLER: 'ALREADY_SELLER',
  SELLER_PROFILE_NOT_FOUND: 'SELLER_PROFILE_NOT_FOUND',
  SELLER_PROFILE_FETCHED: 'SELLER_PROFILE_FETCHED',
  SELLER_NOT_FOUND: 'SELLER_NOT_FOUND',
  SELLER_FETCHED: 'SELLER_FETCHED',
  SELLER_DASHBOARD_FETCHED: 'SELLER_DASHBOARD_FETCHED',
} as const;

// ==========================================
// KVKK
// ==========================================
export const KVKK = {
  CONSENT_CREATED: 'CONSENT_CREATED',
  CONSENT_LIST: 'CONSENT_LIST',
  INVALID_CONSENT_TYPE: 'INVALID_CONSENT_TYPE',
} as const;

// ==========================================
// Product
// ==========================================
export const PRODUCT = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_ACTIVATION_FAILED: 'PRODUCT_ACTIVATION_FAILED',
  PRODUCT_IN_AUCTION: 'PRODUCT_IN_AUCTION',
  SELLER_REQUIRED: 'SELLER_REQUIRED',
  NOT_PRODUCT_OWNER: 'NOT_PRODUCT_OWNER',
  IMAGE_UPLOADED: 'IMAGE_UPLOADED',
  IMAGE_DELETED: 'IMAGE_DELETED',
  MAX_IMAGES_REACHED: 'MAX_IMAGES_REACHED',
  FILE_REQUIRED: 'FILE_REQUIRED',
  LISTING_DRAFT_CREATED: 'LISTING_DRAFT_CREATED',
  LISTING_DRAFT_UPDATED: 'LISTING_DRAFT_UPDATED',
  LISTING_DRAFT_FETCHED: 'LISTING_DRAFT_FETCHED',
  LISTING_DRAFT_LISTED: 'LISTING_DRAFT_LISTED',
  LISTING_DRAFT_DELETED: 'LISTING_DRAFT_DELETED',
  LISTING_DRAFT_PUBLISHED: 'LISTING_DRAFT_PUBLISHED',
  LISTING_DRAFT_NOT_FOUND: 'LISTING_DRAFT_NOT_FOUND',
} as const;

// ==========================================
// Auction
// ==========================================
export const AUCTION = {
  AUCTION_CREATED: 'AUCTION_CREATED',
  AUCTION_UPDATED: 'AUCTION_UPDATED',
  AUCTION_PUBLISHED: 'AUCTION_PUBLISHED',
  AUCTION_CANCELLED: 'AUCTION_CANCELLED',
  AUCTION_LIST: 'AUCTION_LIST',
  AUCTION_FETCHED: 'AUCTION_FETCHED',
  AUCTION_BIDS_FETCHED: 'AUCTION_BIDS_FETCHED',
  AUCTION_RESULT_FETCHED: 'AUCTION_RESULT_FETCHED',
  AUCTION_WINNER_PAYMENT_COMPLETED: 'AUCTION_WINNER_PAYMENT_COMPLETED',
  AUCTION_WINNER_PAYMENT_SKIPPED: 'AUCTION_WINNER_PAYMENT_SKIPPED',
  AUCTION_FINALIZATION_RETRIED: 'AUCTION_FINALIZATION_RETRIED',
  AUCTION_FINALIZATION_SKIPPED: 'AUCTION_FINALIZATION_SKIPPED',
  AUCTION_NOT_FOUND: 'AUCTION_NOT_FOUND',
  AUCTION_NOT_ACTIVE: 'AUCTION_NOT_ACTIVE',
  AUCTION_ENDED: 'AUCTION_ENDED',
  BID_ACCEPTED: 'BID_ACCEPTED',
  BID_WITHDRAWN: 'BID_WITHDRAWN',
  BID_WITHDRAWAL_NOT_ALLOWED: 'BID_WITHDRAWAL_NOT_ALLOWED',
  CANNOT_BID_OWN: 'CANNOT_BID_OWN',
  BID_TOO_LOW: 'BID_TOO_LOW',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  NOT_SELLER: 'NOT_SELLER',
  ACTIVE_AUCTION_EXISTS: 'ACTIVE_AUCTION_EXISTS',
} as const;

// ==========================================
// Category
// ==========================================
export const CATEGORY = {
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_SEEDED: 'CATEGORY_SEEDED',
} as const;

// ==========================================
// Wallet
// ==========================================
export const WALLET = {
  BALANCE_FETCHED: 'BALANCE_FETCHED',
  HOLDS_FETCHED: 'HOLDS_FETCHED',
  WALLET_HISTORY_FETCHED: 'WALLET_HISTORY_FETCHED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
} as const;

// ==========================================
// Ledger / Financial
// ==========================================
export const LEDGER = {
  LEDGER_ENTRY_POSTED: 'LEDGER_ENTRY_POSTED',
  LEDGER_UNBALANCED: 'LEDGER_UNBALANCED',
} as const;

// ==========================================
// Payout
// ==========================================
export const PAYOUT = {
  PAYOUT_REQUEST_CREATED: 'PAYOUT_REQUEST_CREATED',
  PAYOUT_REQUEST_FETCHED: 'PAYOUT_REQUEST_FETCHED',
  PAYOUT_REQUEST_APPROVED: 'PAYOUT_REQUEST_APPROVED',
  PAYOUT_REQUEST_REJECTED: 'PAYOUT_REQUEST_REJECTED',
  PAYOUT_REQUEST_INVALID_STATUS: 'PAYOUT_REQUEST_INVALID_STATUS',
} as const;

// ==========================================
// Payment
// ==========================================
export const PAYMENT = {
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_WEBHOOK_PROCESSED: 'PAYMENT_WEBHOOK_PROCESSED',
  PAYMENT_WEBHOOK_DUPLICATE: 'PAYMENT_WEBHOOK_DUPLICATE',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',
  PAYMENT_REFUND_REQUESTED: 'PAYMENT_REFUND_REQUESTED',
} as const;

// ==========================================
// Order
// ==========================================
export const ORDER = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_FETCHED: 'ORDER_FETCHED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_TRANSITIONED: 'ORDER_TRANSITIONED',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_DELIVERY_CONFIRMED: 'ORDER_DELIVERY_CONFIRMED',
  ORDER_AMOUNT_MISMATCH: 'ORDER_AMOUNT_MISMATCH',
  ORDER_CURRENCY_MISMATCH: 'ORDER_CURRENCY_MISMATCH',
  ORDER_PRODUCT_SELLER_MISMATCH: 'ORDER_PRODUCT_SELLER_MISMATCH',
  ORDER_BUYER_MISMATCH: 'ORDER_BUYER_MISMATCH',
  ORDER_NOT_PAYABLE: 'ORDER_NOT_PAYABLE',
  CANNOT_BUY_OWN_PRODUCT: 'CANNOT_BUY_OWN_PRODUCT',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  RETURN_DELIVERED: 'RETURN_DELIVERED',
  RETURN_REFUND_PENDING: 'RETURN_REFUND_PENDING',
  RETURN_REFUNDED: 'RETURN_REFUNDED',
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
} as const;

// ==========================================
// Cargo
// ==========================================
export const CARGO = {
  CARGO_TRACKING_CREATED: 'CARGO_TRACKING_CREATED',
  CARGO_TRACKING_FETCHED: 'CARGO_TRACKING_FETCHED',
  CARGO_EVENTS_FETCHED: 'CARGO_EVENTS_FETCHED',
  CARGO_STATUS_TRANSITIONED: 'CARGO_STATUS_TRANSITIONED',
} as const;

// ==========================================
// Notification
// ==========================================
export const NOTIFICATION = {
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_FETCHED: 'NOTIFICATION_FETCHED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_PUSH_SENT: 'NOTIFICATION_PUSH_SENT',
  NOTIFICATION_PUSH_FAILED: 'NOTIFICATION_PUSH_FAILED',
  NOTIFICATION_DUPLICATE: 'NOTIFICATION_DUPLICATE',
  NOTIFICATION_PREFERENCES_FETCHED: 'NOTIFICATION_PREFERENCES_FETCHED',
  NOTIFICATION_PREFERENCES_UPDATED: 'NOTIFICATION_PREFERENCES_UPDATED',
} as const;

// ==========================================
// Negotiation / Ask Price
// ==========================================
export const NEGOTIATION = {
  NEGOTIATION_CREATED: 'NEGOTIATION_CREATED',
  NEGOTIATION_FETCHED: 'NEGOTIATION_FETCHED',
  NEGOTIATION_LISTED: 'NEGOTIATION_LISTED',
  NEGOTIATION_CLOSED: 'NEGOTIATION_CLOSED',
  NEGOTIATION_REPORTED: 'NEGOTIATION_REPORTED',
  NEGOTIATION_ADMIN_VIEWED: 'NEGOTIATION_ADMIN_VIEWED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_BLOCKED: 'MESSAGE_BLOCKED',
  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_INVALID_STATUS: 'OFFER_INVALID_STATUS',
  NEGOTIATION_FORBIDDEN: 'NEGOTIATION_FORBIDDEN',
  NEGOTIATION_NOT_FOUND: 'NEGOTIATION_NOT_FOUND',
  ASK_PRICE_NOT_ENABLED: 'ASK_PRICE_NOT_ENABLED',
} as const;

// ==========================================
// Search & Favorites
// ==========================================
export const SEARCH = {
  SEARCH_PRODUCTS_SUCCESS: 'SEARCH_PRODUCTS_SUCCESS',
  SEARCH_AUCTIONS_SUCCESS: 'SEARCH_AUCTIONS_SUCCESS',
  SEARCH_UNIFIED_SUCCESS: 'SEARCH_UNIFIED_SUCCESS',
  FAVORITES_LISTED: 'FAVORITES_LISTED',
  FAVORITE_ADDED: 'FAVORITE_ADDED',
  FAVORITE_REMOVED: 'FAVORITE_REMOVED',
} as const;

// ==========================================
// Cart
// ==========================================
export const CART = {
  CART_FETCHED: 'CART_FETCHED',
  CART_ITEM_ADDED: 'CART_ITEM_ADDED',
  CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
  CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
  CART_CLEARED: 'CART_CLEARED',
  ADMIN_CARTS_FETCHED: 'ADMIN_CARTS_FETCHED',
  ADMIN_CART_ITEMS_FETCHED: 'ADMIN_CART_ITEMS_FETCHED',
} as const;

// ==========================================
// Admin
// ==========================================
export const ADMIN = {
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ADMIN_AUDIT_FETCHED: 'ADMIN_AUDIT_FETCHED',
  ADMIN_SETTING_UPDATED: 'ADMIN_SETTING_UPDATED',
  ADMIN_QUEUE_FETCHED: 'ADMIN_QUEUE_FETCHED',
  ADMIN_REPORT_EXPORTED: 'ADMIN_REPORT_EXPORTED',
  ADMIN_VARIANT_NUMBERS_FETCHED: 'ADMIN_VARIANT_NUMBERS_FETCHED',
  ADMIN_VARIANT_NUMBER_CREATED: 'ADMIN_VARIANT_NUMBER_CREATED',
  ADMIN_VARIANT_NUMBER_UPDATED: 'ADMIN_VARIANT_NUMBER_UPDATED',
  ADMIN_VARIANT_NUMBER_DELETED: 'ADMIN_VARIANT_NUMBER_DELETED',
} as const;

// ==========================================
// Ads
// ==========================================
export const ADS = {
  AD_PACKAGE_CREATED: 'AD_PACKAGE_CREATED',
  AD_REQUEST_CREATED: 'AD_REQUEST_CREATED',
  AD_FUNDS_RESERVED: 'AD_FUNDS_RESERVED',
  AD_APPROVED: 'AD_APPROVED',
  AD_REJECTED: 'AD_REJECTED',
  AD_PUBLISHED: 'AD_PUBLISHED',
  AD_CANCELLED: 'AD_CANCELLED',
  AD_SLOT_CALENDAR_FETCHED: 'AD_SLOT_CALENDAR_FETCHED',
  AD_SLOT_CONFLICTS_FETCHED: 'AD_SLOT_CONFLICTS_FETCHED',
  AD_SLOT_CONFLICT: 'AD_SLOT_CONFLICT',
  SPONSORED_CONTENT_FETCHED: 'SPONSORED_CONTENT_FETCHED',
} as const;

// ==========================================
// Campaign
// ==========================================
export const CAMPAIGN = {
  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED: 'CAMPAIGN_UPDATED',
  CAMPAIGN_OPTED_IN: 'CAMPAIGN_OPTED_IN',
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_STATUS_UPDATED: 'COUPON_STATUS_UPDATED',
  COUPON_APPLIED: 'COUPON_APPLIED',
  COUPON_ALREADY_USED: 'COUPON_ALREADY_USED',
  DISCOUNT_CALCULATED: 'DISCOUNT_CALCULATED',
} as const;

// ==========================================
// Membership
// ==========================================
export const MEMBERSHIP = {
  MEMBERSHIP_PACKAGE_CREATED: 'MEMBERSHIP_PACKAGE_CREATED',
  MEMBERSHIP_PACKAGES_FETCHED: 'MEMBERSHIP_PACKAGES_FETCHED',
  MEMBERSHIP_UPGRADE_STARTED: 'MEMBERSHIP_UPGRADE_STARTED',
  MEMBERSHIP_CHANGED: 'MEMBERSHIP_CHANGED',
  MEMBERSHIP_GRACE_STARTED: 'MEMBERSHIP_GRACE_STARTED',
  MEMBERSHIP_DOWNGRADED: 'MEMBERSHIP_DOWNGRADED',
} as const;

// ==========================================
// Trust
// ==========================================
export const TRUST = {
  TRUST_SCORE_UPDATED: 'TRUST_SCORE_UPDATED',
  TRUST_BADGE_FETCHED: 'TRUST_BADGE_FETCHED',
  TRUST_FLAG_CREATED: 'TRUST_FLAG_CREATED',
  RESTRICTION_APPLIED: 'RESTRICTION_APPLIED',
  RESTRICTION_RESOLVED: 'RESTRICTION_RESOLVED',
  TRUST_REVIEWED: 'TRUST_REVIEWED',
} as const;

// ==========================================
// Mobile Experience
// ==========================================
export const MOBILE = {
  MOBILE_CONFIG_DRAFT_FETCHED: 'MOBILE_CONFIG_DRAFT_FETCHED',
  MOBILE_CONFIG_DRAFT_UPDATED: 'MOBILE_CONFIG_DRAFT_UPDATED',
  MOBILE_CONFIG_PUBLISHED: 'MOBILE_CONFIG_PUBLISHED',
  MOBILE_CONFIG_PUBLISHED_FETCHED: 'MOBILE_CONFIG_PUBLISHED_FETCHED',
  MOBILE_CONFIG_VERSION_CONFLICT: 'MOBILE_CONFIG_VERSION_CONFLICT',
} as const;

// ==========================================
// Content Studio
// ==========================================
export const CONTENT = {
  CONTENT_STUDIO_FETCHED: 'CONTENT_STUDIO_FETCHED',
  CONTENT_STUDIO_UPDATED: 'CONTENT_STUDIO_UPDATED',
  PUBLIC_BLOGS_FETCHED: 'PUBLIC_BLOGS_FETCHED',
} as const;

// ==========================================
// Generic
// ==========================================
export const GENERIC = {
  SUCCESS: 'SUCCESS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT: 'RATE_LIMIT',
} as const;

// Tüm kodları birleştir — type-safe kullanım
export const RC = {
  ...AUTH,
  ...USER,
  ...SELLER,
  ...KVKK,
  ...PRODUCT,
  ...AUCTION,
  ...CATEGORY,
  ...WALLET,
  ...LEDGER,
  ...PAYOUT,
  ...PAYMENT,
  ...ORDER,
  ...CARGO,
  ...NOTIFICATION,
  ...NEGOTIATION,
  ...SEARCH,
  ...CART,
  ...ADMIN,
  ...ADS,
  ...CAMPAIGN,
  ...MEMBERSHIP,
  ...TRUST,
  ...MOBILE,
  ...CONTENT,
  ...GENERIC,
} as const;

export type ResponseCode = (typeof RC)[keyof typeof RC];
