import { StyleSheet, Dimensions } from 'react-native';
import { Colors, FontFamily, FontSize, Spacing, BorderRadius, Shadows } from '../../constants/theme';
const { width: SCREEN_WIDTH } = Dimensions.get('window');
const SQUARE_SIZE = (SCREEN_WIDTH - 16 * 3) / 2;

export const styles = StyleSheet.create({
  // ─── Square variant ───
  squareCard: {
    width: SQUARE_SIZE,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.slate200,
    ...Shadows.md,
  },
  squareImage: {
    width: SQUARE_SIZE,
    height: SQUARE_SIZE,
    backgroundColor: Colors.surfaceContainerLow,
  },
  squareImageContainer: {
    width: SQUARE_SIZE,
    height: SQUARE_SIZE,
    position: 'relative',
  },
  squareBody: {
    padding: Spacing.md,
    flex: 1,
    minHeight: 84, // Ensure identical body height across cards for price alignment
  },
  squareFooter: {
    marginTop: 'auto',
  },
  squareBadge: {
    alignSelf: 'flex-start',
    backgroundColor: `${Colors.primary}16`,
    borderRadius: BorderRadius.full,
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    marginBottom: Spacing.xs,
    overflow: 'hidden',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
  },
  squareTitle: {
    fontSize: FontSize.caption,
    fontFamily: FontFamily.bodySemiBold,
    color: Colors.onSurface,
    lineHeight: 19,
    marginBottom: Spacing.xs,
  },
  squarePrice: {
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.price,
    fontWeight: '400',
    color: Colors.onSurface,
  },
  squareCtaHint: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  squareAskPriceBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: `${Colors.primary}12`,
    borderColor: `${Colors.primary}1A`,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  squareAskPriceText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    fontWeight: '700',
  },

  // ─── Grid variant ───
  gridCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius['2xl'],
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.slate200,
    ...Shadows.md,
    minHeight: 268,
  },
  gridImageContainer: {
    height: 160,
    backgroundColor: Colors.surfaceContainerLow,
    position: 'relative',
  },
  gridImage: {
    width: '100%',
    height: '100%',
  },
  gridBody: {
    padding: Spacing.lg,
    minHeight: 108,
    flex: 1,
  },
  gridBadge: {
    alignSelf: 'flex-start',
    backgroundColor: `${Colors.primary}16`,
    borderRadius: BorderRadius.full,
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    marginBottom: Spacing.xs,
    overflow: 'hidden',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
  },
  gridTitle: {
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodySemiBold,
    fontWeight: '600',
    color: Colors.onSurface,
    marginBottom: Spacing.xs,
    lineHeight: 20,
    minHeight: 40,
  },
  gridCategory: {
    fontSize: FontSize.caption,
    fontFamily: FontFamily.body,
    color: Colors.onSurfaceVariant,
    marginBottom: Spacing.sm,
    minHeight: 16,
  },
  gridFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 'auto',
  },
  gridPrice: {
    fontSize: FontSize.bodyXl,
    fontFamily: FontFamily.price,
    fontWeight: '400',
    color: Colors.onSurface,
  },
  gridCtaHint: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  gridAskPriceButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    gap: Spacing.xs,
    minHeight: 32,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  gridAskPriceText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    fontWeight: '700',
  },
  geoBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: Colors.secondary,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    gap: Spacing.xs,
    left: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    position: 'absolute',
    top: Spacing.sm,
  },
  geoBadgeText: {
    color: Colors.white,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    fontWeight: '700',
  },
  geoBadgeLogo: {
    height: 32,
    width: 32,
  },
  geoBadgeLogosRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    left: Spacing.sm,
    position: 'absolute',
    top: Spacing.sm,
  },
  favoriteButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderRadius: BorderRadius.full,
    height: 32,
    justifyContent: 'center',
    position: 'absolute',
    right: Spacing.sm,
    top: Spacing.sm,
    width: 32,
  },
});
