import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../../constants/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    paddingBottom: Spacing.xxl,
  },
  heroCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}24`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    padding: Spacing.lg,
    ...Shadows.md,
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  heroBadge: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    letterSpacing: 0.7,
  },
  heroCountPill: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  heroCountText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  heroTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
    marginBottom: Spacing.xs,
  },
  heroSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    lineHeight: 18,
  },
  stepCard: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    padding: Spacing.lg,
    ...Shadows.md,
  },
  inputGroup: {
    marginBottom: Spacing.lg,
  },
  inputLabel: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    letterSpacing: 0.5,
    marginBottom: Spacing.xs,
    textTransform: 'uppercase',
  },
  helperText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
    marginTop: Spacing.xs,
  },
  infoCard: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}0D`,
    borderColor: `${Colors.primary}18`,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  infoCardLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  infoCardTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  infoCardSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  infoCardValue: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
  },
  input: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.outlineVariant,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  textareaInput: {
    minHeight: 112,
    textAlignVertical: 'top',
  },
  inlineRow: {
    flexDirection: 'row',
    gap: Spacing.base,
  },
  inlineBlock: {
    flex: 1,
  },
  categorySelector: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.outlineVariant,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  categorySelectorLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categoryMediaWrap: {
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    height: 30,
    overflow: 'hidden',
    width: 30,
  },
  categoryMediaImage: {
    height: '100%',
    width: '100%',
  },
  categorySelectorText: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  categorySelectorPlaceholder: {
    color: Colors.onSurfaceVariant,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  toggleCard: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  toggleTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  toggleSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: Colors.outline,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  chip: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  chipActive: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  chipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  chipTextActive: {
    color: Colors.primary,
  },
  advancedToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.base,
  },
  advancedToggleText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  imagePickerButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    borderStyle: 'dashed',
    borderWidth: 1,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.xxl,
  },
  imagePickerTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
    marginTop: Spacing.sm,
  },
  imagePickerSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
    marginTop: Spacing.xs,
    textAlign: 'center',
  },
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.base,
  },
  imageCard: {
    borderRadius: BorderRadius.xl,
    height: 92,
    overflow: 'hidden',
    position: 'relative',
    width: 92,
  },
  imagePreview: {
    height: '100%',
    width: '100%',
  },
  imageRemoveButton: {
    alignItems: 'center',
    backgroundColor: `${Colors.slate900}B3`,
    borderRadius: BorderRadius.full,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: Spacing.xs,
    top: Spacing.xs,
    width: 28,
  },
  summaryCard: {
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    marginBottom: Spacing.sm,
    padding: Spacing.base,
  },
  summaryLabel: {
    color: Colors.slate500,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  summaryValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  navigationRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.base,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.xl,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
  },
  secondaryButtonText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: Colors.secondary,
    borderRadius: BorderRadius.xl,
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    minHeight: 54,
    ...Shadows.colored(Colors.secondary),
  },
  primaryButtonDisabled: {
    backgroundColor: Colors.slate300,
    elevation: 0,
    shadowOpacity: 0,
  },
  primaryButtonText: {
    color: Colors.white,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  categoryModalBackdrop: {
    backgroundColor: `${Colors.slate900}73`,
    flex: 1,
  },
  categoryModalScreen: {
    backgroundColor: Colors.white,
    flex: 1,
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.xl,
  },
  categoryModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.base,
  },
  categoryModalTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
  },
  categoryModalCloseButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  categorySearchWrapper: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.base,
    paddingHorizontal: Spacing.base,
  },
  categorySearchInput: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    paddingVertical: Spacing.md,
  },
  rootCategoryRow: {
    gap: Spacing.sm,
    paddingBottom: Spacing.base,
  },
  rootCategoryChip: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.base,
    paddingVertical: 10,
  },
  rootCategoryChipSelected: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  rootCategoryChipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  rootCategoryChipTextSelected: {
    color: Colors.primary,
  },
  subcategoryTitle: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    marginBottom: Spacing.sm,
    marginTop: 2,
  },
  categoryListContent: {
    paddingBottom: Spacing.xl,
  },
  categoryListItem: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    minHeight: 68,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  categoryListItemSelected: {
    backgroundColor: `${Colors.primary}0D`,
    borderColor: Colors.primary,
  },
  categoryListItemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categoryMediaWrapLarge: {
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    height: 42,
    overflow: 'hidden',
    width: 42,
  },
  categoryListItemText: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodyLg,
    paddingRight: Spacing.sm,
  },
  categoryListItemTextSelected: {
    color: Colors.primary,
  },
  categoryEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xl,
  },
  categoryEmptyStateText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
  productsCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}18`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.base,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.md,
  },
  productsCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.base,
  },
  productsCardTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
  },
  productsCardSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  productRow: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    minHeight: 60,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  productRowInfo: {
    flex: 1,
    paddingRight: Spacing.base,
  },
  productRowTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  productRowSub: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  statusPill: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  statusPillText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
  },
  emptyProducts: {
    alignItems: 'center',
    paddingVertical: Spacing.lg,
  },
  emptyProductsText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
});
