import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontFamily, FontSize, Shadows, Spacing } from '../../../constants/theme';

export const styles = StyleSheet.create({
  page: {
    backgroundColor: Colors.background,
    flex: 1,
  },
  scrollContent: {
    paddingTop: Spacing.xs,
    paddingBottom: 132,
  },
  heroCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}36`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    padding: Spacing.lg,
    ...Shadows.lg,
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  heroBadge: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.xs,
    letterSpacing: 0.7,
  },
  heroCountPill: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}10`,
    borderColor: `${Colors.primary}26`,
    borderWidth: 1,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  heroCountText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  heroTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
    lineHeight: 28,
    marginBottom: 6,
  },
  heroSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
    lineHeight: 20,
  },
  stepCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}24`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.base,
    padding: Spacing.lg,
    ...Shadows.lg,
  },
  inputGroup: {
    marginBottom: Spacing.lg,
  },
  inputLabel: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    letterSpacing: 0.5,
    marginBottom: Spacing.xs,
    textTransform: 'uppercase',
  },
  helperText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
    marginTop: Spacing.xs,
  },
  infoCard: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}0D`,
    borderColor: `${Colors.primary}18`,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  infoCardLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  infoCardTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  infoCardSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  infoCardValue: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
  },
  input: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    color: Colors.onSurface,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    minHeight: 52,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    ...Shadows.sm,
  },
  selectorInput: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 50,
    paddingHorizontal: Spacing.base,
    ...Shadows.sm,
  },
  selectorInputText: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    paddingRight: Spacing.sm,
  },
  selectorInputPlaceholder: {
    color: Colors.slate400,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    paddingRight: Spacing.sm,
  },
  textareaInput: {
    minHeight: 112,
    textAlignVertical: 'top',
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.base,
  },
  inlineBlock: {
    flex: 1,
    minWidth: 0,
  },
  categorySelector: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate300,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    ...Shadows.sm,
  },
  categorySelectorLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categoryMediaWrap: {
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    height: 30,
    overflow: 'hidden',
    width: 30,
  },
  categoryMediaImage: {
    height: '100%',
    width: '100%',
  },
  categorySelectorText: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  categorySelectorPlaceholder: {
    color: Colors.onSurfaceVariant,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.body,
  },
  toggleCard: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
    ...Shadows.sm,
  },
  toggleTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  toggleSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: Colors.outline,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  chipRowScroll: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: Spacing.sm,
    paddingRight: Spacing.base,
  },
  chip: {
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: Spacing.base,
    paddingVertical: 7,
    ...Shadows.sm,
  },
  chipActive: {
    backgroundColor: `${Colors.primary}12`,
    borderColor: Colors.primary,
  },
  chipText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  chipTextActive: {
    color: Colors.primary,
  },
  advancedToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.base,
  },
  advancedToggleText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  imagePickerButton: {
    alignItems: 'center',
    backgroundColor: `${Colors.primary}08`,
    borderColor: `${Colors.primary}5E`,
    borderRadius: BorderRadius.xl,
    borderStyle: 'dashed',
    borderWidth: 1,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.xxl,
    ...Shadows.sm,
  },
  imagePickerTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyXl,
    marginTop: Spacing.sm,
  },
  imagePickerSub: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    lineHeight: 18,
    marginTop: Spacing.xs,
    textAlign: 'center',
  },
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.base,
  },
  imageCard: {
    borderRadius: BorderRadius.xl,
    height: 92,
    overflow: 'hidden',
    position: 'relative',
    width: 92,
  },
  imagePreview: {
    height: '100%',
    width: '100%',
  },
  imageRemoveButton: {
    alignItems: 'center',
    backgroundColor: `${Colors.slate900}B3`,
    borderRadius: BorderRadius.full,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: Spacing.xs,
    top: Spacing.xs,
    width: 28,
  },
  summaryCard: {
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    marginBottom: Spacing.sm,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  summaryLabel: {
    color: Colors.slate500,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  summaryValue: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  navigationRow: {
    backgroundColor: Colors.surfaceContainerLowest,
    borderTopColor: `${Colors.primary}1F`,
    borderTopWidth: 1,
    borderTopLeftRadius: BorderRadius['2xl'],
    borderTopRightRadius: BorderRadius['2xl'],
    flexDirection: 'row',
    gap: Spacing.md,
    paddingHorizontal: Spacing.base,
    paddingBottom: Spacing.base,
    paddingTop: Spacing.sm,
    ...Shadows.tabBar,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
    marginBottom: 5,
  },
  secondaryButtonText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    justifyContent: 'center',
    minHeight: 56,
    marginBottom: 5,
    ...Shadows.colored(Colors.primary),
  },
  primaryButtonAuction: {
    backgroundColor: Colors.secondary,
    ...Shadows.colored(Colors.secondary),
  },
  primaryButtonDisabled: {
    backgroundColor: Colors.slate300,
    elevation: 0,
    shadowOpacity: 0,
  },
  primaryButtonText: {
    color: Colors.white,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  categoryModalBackdrop: {
    backgroundColor: `${Colors.slate900}73`,
    flex: 1,
  },
  bottomSheetBackdrop: {
    backgroundColor: `${Colors.slate900}4D`,
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheetDismissArea: {
    flex: 1,
  },
  bottomSheetContainer: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius['2xl'],
    borderTopRightRadius: BorderRadius['2xl'],
    maxHeight: '78%',
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.sm,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    backgroundColor: Colors.slate300,
    borderRadius: BorderRadius.full,
    height: 4,
    marginBottom: Spacing.sm,
    width: 44,
  },
  categoryModalSafeArea: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  categoryModalScreen: {
    backgroundColor: Colors.white,
    flex: 1,
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.sm,
  },
  categoryModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.base,
  },
  categoryModalHeaderTextWrap: {
    flex: 1,
    paddingRight: Spacing.base,
  },
  categoryModalTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.headlineBlack,
    fontSize: FontSize.titleSm,
  },
  categoryModalSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  categoryModalCloseButton: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderRadius: BorderRadius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  categorySearchWrapper: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.base,
    paddingHorizontal: Spacing.base,
  },
  categorySearchInput: {
    color: Colors.onSurface,
    flex: 1,
    fontFamily: FontFamily.body,
    fontSize: FontSize.bodyLg,
    paddingVertical: Spacing.md,
  },
  categorySearchClearButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  rootCategoryTitle: {
    color: Colors.slate600,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
    marginBottom: Spacing.xs,
    textTransform: 'uppercase',
  },
  rootCategoryListContent: {
    paddingBottom: Spacing.base,
  },
  rootCategoryListItem: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: Spacing.sm,
    minHeight: 72,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
  },
  rootCategoryListIconWrap: {
    alignItems: 'center',
    borderRadius: BorderRadius.lg,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  rootCategoryListContentWrap: {
    flex: 1,
    marginHorizontal: Spacing.base,
  },
  rootCategoryListTitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  rootCategoryListMeta: {
    color: Colors.slate500,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  subcategoryHeader: {
    marginBottom: Spacing.sm,
  },
  subcategoryBackButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: `${Colors.primary}0D`,
    borderRadius: BorderRadius.full,
    flexDirection: 'row',
    gap: Spacing.xs,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  subcategoryBackText: {
    color: Colors.primary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.caption,
  },
  subcategoryTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
  },
  categoryListContent: {
    paddingBottom: Spacing.xl,
  },
  categoryListItem: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate100,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    minHeight: 68,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  categoryListItemSelected: {
    backgroundColor: `${Colors.primary}0D`,
    borderColor: Colors.primary,
  },
  categoryListItemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  categoryMediaWrapLarge: {
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  categoryIconWrapLarge: {
    alignItems: 'center',
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  provinceIconWrap: {
    backgroundColor: `${Colors.primary}12`,
  },
  categoryListItemText: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    flex: 1,
  },
  categoryListItemTextSelected: {
    color: Colors.primary,
  },
  categoryEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xl,
  },
  categoryEmptyStateText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
  productsCard: {
    backgroundColor: Colors.white,
    borderColor: `${Colors.primary}30`,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.xs,
    marginBottom: Spacing.base,
    padding: Spacing.base,
    ...Shadows.lg,
  },
  productsCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.base,
  },
  productsCardTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodyLg,
  },
  productsCardSubtitle: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.body,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  productRow: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
    minHeight: 60,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    ...Shadows.sm,
  },
  productRowSelected: {
    backgroundColor: `${Colors.primary}0D`,
    borderColor: Colors.primary,
  },
  productRowInfo: {
    flex: 1,
    paddingRight: Spacing.base,
  },
  productRowTitle: {
    color: Colors.onSurface,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  productRowSub: {
    color: Colors.primary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  statusPill: {
    backgroundColor: Colors.surfaceContainerLow,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  statusPillText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.xs,
  },
  emptyProducts: {
    alignItems: 'center',
    paddingVertical: Spacing.lg,
  },
  emptyProductsCompact: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceContainerLowest,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.xs,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: Spacing.base,
  },
  emptyProductsText: {
    color: Colors.onSurfaceVariant,
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.caption,
  },
});
